### ISSUE TITLE
redirect_url for OAuth?

### ISSUE THREAD

**Issue by RobertoMaurizzi** [alpacahq/alpaca-rn-mobile#21]
### Description
I'm not an expert in React, native (or otherwise) but from what I can understand from Alpaca's OAuth documentation and by reading your application's code (`App/Containers/User/StartScreen.js` lines 40 and 124) the value I should use for "Redirect URIs" when registering a new OAuth App is `alpacamobile://oauth`. However the form says the URI needs to start with http:// or https://

How to use OAuth with this React Native application? Is there a http://localhost:<port>/<path> that should be used now?

### How to repeat issue and example

* Go to https://app.alpaca.markets/brokerage/apps/manage and login
* Click on Create New App
* Fill the required fields and try to type `alpacamobile://oauth` in the **Redirect URIs** field
* the form will show
![image](https://user-images.githubusercontent.com/451686/78128511-05ff1e80-7451-11ea-96f2-e4814c801e28.png)

### Additional Information

I'm building this repository according to your README.md without any change other than setting my AUTH_CLIEND_ID and AUTH_CLIENT_SECRET. I'm able to get a build on a mobile.

* React Native version: 0.59.10
* Platform: Android
* Development Operating System: MacOS 10.15.4
* Dev tools: Android Studio 3.6, Android SDK 28 and 23

**Comment by risingworld777** [comment]
@RobertoMaurizzi   We noticed this issue and are trying to fix.  We will let you know once we fix the issue.

**Comment by risingworld777** [comment]
@RobertoMaurizzi  This issue should be fixed now.
